### ISSUE TITLE
Support `no utf8::all`

### ISSUE THREAD

**Issue by doherty** [doherty/utf8-all#33]
@HayoBaan commented 5 days ago [Jan 3, 2015]

On top of what has been changed already, I'm also thinking of adding support for no utf8::all to (temporarily) disable utf-8 support. Not yet sure if we can unimport things like charnames etc. though…
What are your thoughts?

**Comment by doherty** [comment]
@HayoBaan: Can you create some test cases to illustrate what needs to be done? I'm perfectly happy to accept pull requests (hopefully faster than the last one you sent me -- let's try to do smaller units of work this time).

**Comment by HayoBaan** [comment]
@doherty I've been thinking about this a bit more and most things can not (or should not) be undone.
I think the only thing we should really be doing is resetting the compile hint so we have an easy way to prevent the utf8 encoding/decoding of the replaced functions. This would mean a simple unimport like this:
```sub unimport { ## no critic (Subroutines::ProhibitBuiltinHomonyms)
    # If run on the dos/os2/windows platform, ignore overriding functions silently.
    # These platforms do have (proper) utf-8 file system suppport...
    unless ($^O =~ /MSWin32|cygwin|dos|os2/) {
        $^H{utf8::all} = 0; # Set compiler hint that we should not use the utf-8 version
    }

    return;
}``` (I'm also proposing to just use one C<utf8::all> hint and not the separate (and quite unnecessary) ones we now have.)
The test case for this could be a simple extension of e.g., the readdir test. If you like I can work on this. (it will take a while though as I will be abroad for some time the coming period)

**Comment by HayoBaan** [comment]
It turned out some more had to be done to correctly implement `no utf8::all`, but I think I got it.
Working on it made me aware of some bugs in the tests as well… Tests were using 1-byte (unicode) characters, making some tests succeed while in fact they didn't. Other tests were testing the wrong thing (most notably lexical and lexical-again). I have rewritten these tests so they prove what we're after!
Also extended the documentation to explicitly mention that changes to `@ARGV` and the `STDIN`, `STDOUT` and `STDERR` are always global, not lexical!
